### ISSUE TITLE
Popp valve parameters missing

### ISSUE THREAD

**Issue by Aposei** [zigpy/zigpy#840] opened 2021-10-31 11:02 UTC
Hello. I'm a user of Jeedom's zigpy-based zigbee plugin.
Recently the Jeedom team have integrated the Popp radiator valve into the plugin. The parameters obtained from the valve are the local temperature, the setpoint, the head opening and the mode. I have tried to integrate the valve in zigbee2mqtt and I get many more parameters, all listed here:
https://www.zigbee2mqtt.io/devices/701721.html
How to solve this to have all the parameters in zigpy (plugin zigbee / jeedom)?
My apologies if I do not explain well, I do not speak English or I am a computer scientist.
Thanks.

**Comment by MattWestb** [comment] 2021-10-31 12:01
Then looking in the [danfoss quirk](https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/danfoss/thermostat.py) its looks having more or less all attributes and commands implanted.
The question is if Jeedom have patched the quirk for loading the Popp TRV.
If not is you only getting the "standard" functions and not  the extra danfoss is using.

@zoic21 shall we adding the Popp `eT093WRO` and Hive `UK7004240` to the Danfoss Ally quirk so they is getting all the functions that the Ally is having ?

I have asking before in the Danfoss issue but it was no interest doing that but is easy done if user need it.

**Comment by MattWestb** [comment] 2021-10-31 12:03
@Aposei Can you posting the manufacturer and model reported from the device in the zigbee network ?

**Comment by Aposei** [comment] 2021-10-31 12:21
> @Aposei Can you posting the manufacturer and model reported from the device in the zigbee network ?

Is that what you ask of me? I still have it on z2m to test.
![capture](https://user-images.githubusercontent.com/92597237/139582998-321660df-ee7e-4912-9b7d-a1c479ece5a2.png)

**Comment by Aposei** [comment] 2021-11-02 13:03
@MattWestb, this is what I get in the Jeedom plugin

Manufacturer: eT093WRO
Model: eT093WRO

**Comment by zoic21** [comment] 2021-11-02 13:36
Hello,
I'am not sur that Popp had same paramaters as Danfoss it's not the same manufacturer.

**Comment by MattWestb** [comment] 2021-11-02 13:46
Thanks for replay @zoic21  !!

One user have testing with ZHA and lit looks being the same and software but can being running on different releases but the function shall working OK and one Danfoss with the same software version. https://github.com/zigpy/zha-device-handlers/issues/1005#issuecomment-940805715

I giving it one try but having problem finding the right `MODELS_INFO` but we can testing is it loading.

Is it possible to see if the device have loading the right quirk in Jeedom and is the local quirk also working or must patching the docker container or local code ?

**Comment by MattWestb** [comment] 2021-11-02 13:56
@Aposei I have adding the Popp and Hive TRVs to the quirk in my test branch https://github.com/MattWestb/zha-device-handlers/blob/Popp-Hive-TRV/zhaquirks/danfoss/thermostat.py so you can downloading it replacing the original file in you quirk folder or editing the original with the changes.

I dont knowing how to do it best in Jeedom but there devs is knowing that.

Pleas reporting back if its working OK or not !!

**Comment by zoic21** [comment] 2021-11-02 13:57
Very weird, Popp and Danfoss are competitor... 

Yes you can see in Jeedom, in "node configuration" class used by device.

User can add file in quirks folder but it's not easy...

**Comment by MattWestb** [comment] 2021-11-02 14:03
And Hive looks using all Danfoss commands 2:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/af1b1bf7fc10cb9e239c3b4a0c0077bf4ff399d2/devices/hive.js#L153-L155

Can you helping the user testing the updated quirk ?

 If its working OK i doing one pull request for it.

**Comment by Hedda** [comment] 2021-11-02 14:52
Does the official Jeedom Zigbee Plugin depend on zha-device-handlers / zha-quirks as an upstream dependency for quirk(s)?

https://github.com/zigpy/zha-device-handlers

https://pypi.org/project/zha-quirks/

If so then this issue perhaps being in https://github.com/zigpy/zha-device-handlers/issues instead of here in zigpy issues?

**Comment by MattWestb** [comment] 2021-11-02 15:00
Moving or closing issues is one thing for the maintainers of the Zigpy organization and as long i can helping the user is not problem is is not 110% right posted if working well fixing the problem.

Its the Jeedom's devs that have implanting the Danfoss Ally and many more devices in our quirks so i cant complaining and its good four all users of Zigpy system like ZHA and Jeedom is getting better device support so is one win win situation for all.

**Comment by zoic21** [comment] 2021-11-02 15:05
Yes Jeedom use zha-device-handlers / zha-quirks (same as HA). When we do quirks if quirks is fully working we make a PR to zha-device-handlers. I have 4 quirks in testing mode but they don't works at 100% so for now I don't make a PR.

**Comment by Hedda** [comment] 2021-11-02 15:07
> Moving or closing issues is one thing for the maintainers of the Zigpy organization and as long i can helping the user is not problem is is not 110% right posted if working well fixing the problem.
> 
> Its the Jeedom's devs that have implanting the Danfoss Ally and many more devices in our quirks so i cant complaining and its good four all users of Zigpy system like ZHA and Jeedom is getting better device support so is one win win situation for all.

I fully understand that. I'm only suggesting that it would just be good if Jeedom SAS could get the feedback from their users that they should really be referring to [zha-device-handlers / zha-quirks](https://github.com/zigpy/zha-device-handlers) for device compatibility issues/requests instead of zigpy.

**Comment by MattWestb** [comment] 2021-11-02 15:19
@Hedda If not having one instruction how to testing new / updated quirks in Jeedom then is not very likely the Zigpy organisation is merger them because they is completely untested = dont belonging in one production system.

The best is if Jeedom can having one guide for testing quirks in there system then its being very easy or all sides and also the user is knowing to do all things right from the beginning.

**Comment by MattWestb** [comment] 2021-11-02 15:25
@zoic21  I have made one updated guide for editing quirks in HAs docker container that is working but is not for very low skill users https://github.com/zigpy/zha-device-handlers/discussions/693.

If you like you can doing one post in the same discussion or one new one so we can helping the user testing there new device is there systems.

**Comment by Aposei** [comment] 2021-11-02 15:25
@zoic21 I have downloaded the thermostat.py file, do I have to paste it as is in a directory? or is it more complicated than that?

**Comment by zoic21** [comment] 2021-11-02 16:14
You juste have to past it in this folder : /var/www/html/plugins/zigbee/resources/zigbeed/quirks than restart deamon.

I note to add this in documentation.

**Comment by MattWestb** [comment] 2021-11-02 16:27
Is it possible pasting nested quirks like one` __init__.py `  and one `device.py` and the `device.py` is getting data form the ` __init__.py ` or is it  like ZHA that the `device.py` is always getting its data from the installation (container) ?

Some quirks need changes in both for working and good to knowing what is possible and not in Jeedom.

I have writing one note for testing quirks in Jeedom and is updating it for future needs ;-))

**Comment by zoic21** [comment] 2021-11-03 08:55
@Aposei could you please post a snapshot of "node configuration" (first tab),it's display the quirks used by device.
For command you need to change device to danfoss valve for testing.

**Comment by MattWestb** [comment] 2021-11-03 09:20
_Hola buenos dias_ @albalaing !
You is using the Popp TRV with ZHA,

Can you looking if i have doing the device ID OK i the https://github.com/zigpy/zigpy/issues/840#issuecomment-957631371 and if ZHA is loading the quirks for the Popp TRV if installing it as local quirk (or patched in the HA container) ?

Jeedom is also using Zigpy and quirks but  is not  so easy for there user to verified that it working OK.

I like getting it pushed in ZHA so all user can using them with all function implanted in there system :-)))

Thanks in advance !!

**Comment by albalaing** [comment] 2021-11-03 09:35
It recognizes me with these IDs
``  MODELS_INFO: [(DANFOSS, "eTRV0100"),("D5X84YU", "eT093WRO")],  ``
I have copied the quirk of danfoss/thermostat.py in as a local quirk and I have changed the previous line to it. And it works for me the same as danfoss, I also have you.

**Comment by Aposei** [comment] 2021-11-03 09:59
@zoic21 That?

![Screenshot_20211103-103406_Chrome](https://user-images.githubusercontent.com/92597237/140037480-0aef00ea-907a-4559-8d2d-73bf25b6efc8.jpg)

Switching to Danfoss, I get the same, more Fênetre

**Comment by MattWestb** [comment] 2021-11-03 10:07
Thanks for feed back !!

Then i have making the manufacture ID wrong and i shall fixing it i my git.
Then the problem is finding the right for the Hive :-((

I pinging then have finding the right parameters and have doing the update so Jeedom  can testing it 2 :-))

**Comment by MattWestb** [comment] 2021-11-03 10:16
Have updating the git with:
```
        MODELS_INFO: [
            (DANFOSS, "eTRV0100"),
            ("D5X84YU", "eT093WRO"),
            ("DANFOSS", "RV001"),
        ],
```
Then have finding Popp: 
![IMG_Popp TRV](https://user-images.githubusercontent.com/44093812/132020394-4c1aa2f8-259f-4420-ba3a-ee533f15ab15.png)
And Hive: ![IMG_Hive TRV](https://user-images.githubusercontent.com/45408070/87801856-4475e900-c848-11ea-917a-35f9faab2469.PNG)
So very strange Hive is using Danfoss aas manufacture !!

Hope getting it confirmed of some user that is working.

**Comment by Aposei** [comment] 2021-11-05 12:14
Hi, @MattWestb @zoic21 So is there a solution?  Can I contribute something else?

**Comment by MattWestb** [comment] 2021-11-05 12:34
I like having one OK for one user that the Pop is working OK with the changes i have made (the quirk is being loaded by the system for Popp TRVs) then i posting one PR for adding it, but no one have making that, so its on hold from my side.

I think then its being added in ZHA all shall working OK in Jeedom or perhaps need little attention form its devs for getting it working OK.

**Comment by zoic21** [comment] 2021-11-05 13:45
Yes I have some work todo I will add configuration for the valve in next beta.

**Comment by Aposei** [comment] 2021-11-08 08:41
Hi @MattWestb @zoic21. I have re-integrated the Popp thermostat after the latest updates to the Zigbee plugin. I still miss it, compared to when I integrate it into z2m, mainly; battery, keypad_lockout, setpoint_change_source, window_open_external and algorithm_scale_factor.

**Comment by MattWestb** [comment] 2021-11-08 08:51
Can you see if the modified Danfoss quirk is loaded of the system and adding the extra attribute for the device ?

I not sure its working OK until someone can confirming it.

And i think **Zoic21** is planing adding more function for the device in Jeedom but i dont knowing that.

**Comment by Aposei** [comment] 2021-11-08 08:59
> Can you see if the modified Danfoss quirk is loaded of the system and adding the extra attribute for the device ?
> 
> I not sure its working OK until someone can confirming it.
> 
> And i think **Zoic21** is planing adding more function for the device in Jeedom but i dont knowing that.

Yes, I look at it, but I need @zoic21 to tell me where to look at it.

**Comment by zoic21** [comment] 2021-11-08 09:41
Hello,
You need to go "node configuration" (blue button) when you are on the device in Jeedom and you have "classe" label : 
![image](https://user-images.githubusercontent.com/1536036/140719103-dad86223-f1c4-47a5-978d-3262db8ffff0.png)

**Comment by Aposei** [comment] 2021-11-08 09:50
Thanks @zoic21.  This I get.
![Screenshot_20211108-104836_Chrome](https://user-images.githubusercontent.com/92597237/140720363-b265edc6-b7fb-4153-9240-e45fd0dc5aa2.jpg)

**Comment by MattWestb** [comment] 2021-11-08 09:56
The device IDs looks OK but the quirk is not loaded ("D5X84YU", "eT093WRO").
Did you using the second updated version then the first  was wrong ?

**Comment by Aposei** [comment] 2021-11-08 10:45
> The device IDs looks OK but the quirk is not loaded ("D5X84YU", "eT093WRO"). Did you using the second updated version then the first was wrong ?

If you mean the plugin version, I used the latest beta version that came out today

**Comment by MattWestb** [comment] 2021-11-08 10:49
I think it have not being added then the no PR is being merged for the TRVs.
You need adding it by hand or better copy my latest danfoss quirk in your system and restarting it for taking effect.

**Comment by Aposei** [comment] 2021-11-08 18:41
I have downloaded the thermostat.py file, I have copied it to the folder: /var/www/html/plugins/zigbee/resources/zigbeed/quirks
I have integrated the thermostat again and have the same commands
![screenshot](https://user-images.githubusercontent.com/92597237/140799116-e63721f3-1eec-463a-a244-7a25b8853f85.jpg)

**Comment by zoic21** [comment] 2021-11-09 10:16
Hello,
Can you test with danfoss valve configuration ?

**Comment by Aposei** [comment] 2021-11-09 10:50
> Hola, ¿Puedes probar con la configuración de válvulas danfoss?

Yes, I try. But do I have to delete the thermostat.py file or do I keep it?

**Comment by zoic21** [comment] 2021-11-09 12:22
No not on zigpy on jeedom only : 
![image](https://user-images.githubusercontent.com/1536036/140923549-55708373-632a-4295-80ed-2340a94da17b.png)

**Comment by Aposei** [comment] 2021-11-09 12:31
> No, no solo en zigpy en jeedom: ![imagen](https://user-images.githubusercontent.com/1536036/140923549-55708373-632a-4295-80ed-2340a94da17b.png)

Doing that, I have these commands...

![Screenshot_20211109-133053_Chrome](https://user-images.githubusercontent.com/92597237/140924607-dbcab8a2-4c4a-4ce1-9a68-876b803b1dee.jpg)
![Screenshot_20211109-132922_Chrome](https://user-images.githubusercontent.com/92597237/140924431-09eacef3-ea02-4408-8070-c86d7ad0fcdc.jpg)
![Screenshot_20211109-132951_Chrome](https://user-images.githubusercontent.com/92597237/140924489-d806f2a6-3519-43cc-a22b-697ab48b6fb8.jpg)

**Comment by Aposei** [comment] 2021-11-23 08:33
Hello @zoic21 @MattWestb. Some things missing compared to zigbee2mqtt are keypad_lockout, external_measured_room_sensor and algorithm_scale_factor which in the case of z2m it is possible to select from 1 to 10
I'm on the latest beta version of the zigbee plugin

**Comment by zoic21** [comment] 2021-11-23 13:43
Hello,
Can you please open an jeedom ticket, for that it's an issue with jeedom not zigpy.

**Comment by MattWestb** [comment] 2021-11-23 15:58
Thanks @zoic21  !!
The Popp is added in the quirk by one user so it shall working in some weeks without patching then the new device handle is released (for HA 2021.12).

**Comment by Hedda** [comment] 2022-01-26 12:04
@Aposei can this issue be closed now that https://github.com/zigpy/zha-device-handlers/pull/1148 by @hertleinj for Popp D5X84YU  (POPZ701721) has been merged into [zha-device-handlers](https://github.com/zigpy/zha-device-handlers) as part of the 0.0.64 release? Maybe continue in https://github.com/zigpy/zha-device-handlers/issues/1005 if needed?

**Comment by Hedda** [comment] 2022-06-17 06:53
@Aposei Will you please consider closing this issue under the zigpy repository yourself?

Again high-level issues with device compatibility problems such as those you mention should be reported as issue to repository for "[ZHA Device Handlers](https://github.com/zigpy/zha-device-handlers)” (a.k.a. "[zha-quirks](https://pypi.org/project/zha-quirks)") instead of here in zigpy library repository which is only for low-level Zigbee issues:

https://github.com/zigpy/zha-device-handlers/issues

https://github.com/zigpy/zha-device-handlers/blob/dev/README.md

If test now and still have problem then open an issue there -> https://github.com/zigpy/zha-device-handlers/issues/new/choose

**Closed** 2022-06-17 06:57 UTC
