### ISSUE TITLE
[Feature request] Add support to TI CC253X

### ISSUE THREAD

**Issue by leobel96** [zigpy/zigpy#120] opened 2019-01-24 16:36 UTC
Many users opened issues asking to add this device to zigpy but they have been ignored. It's a popular and cheap device and its support in zigpy would be great.

**Comment by Hedda** [comment] 2019-01-25 07:39
@leobel96 your request is a duplicate of existing issue #85 so suggest that you close your and update it.

**Closed** 2019-01-25 09:33 UTC
