### ISSUE TITLE
Cannot pair new devices ZHA/Home Assistant

### ISSUE THREAD

**Issue by stevetz** [zigpy/zigpy#398] opened 2020-05-01 07:07 UTC
I'm trying to add them to my ZHA on Home Assistant - hassio. It has a bunch of Tradfri and Aqara devices already paired - via a cc2531 (passed through to the hassio vm on a Proxmox node). Running core 0.109.1 (upgraded from 107.7 which had the same issues, no change), supervisor fully updated etc.

Every time I try to pair a new device it fails to find anything. and this error is spat out:  

`WARNING (MainThread) [zigpy_cc.zigbee.application] missing tsn from mgmtPermitJoinRsp, maybe not a reply`

**Comment by Adminiuga** [comment] 2020-05-05 18:40
Duplicate of https://github.com/zigpy/zigpy-cc/issues/43
Closing this one.

**Closed by Adminiuga** 2020-05-05 18:40 UTC
