### ISSUE TITLE
New PyPi Release

### ISSUE THREAD

**Issue by cgarwood** [zigpy/zigpy#76] opened 2018-08-16 23:34 UTC
Could we get a new release pushed to PyPi so Home Assistant's requirement can be updated?

**Comment by AndreasBomholtz** [comment] 2018-08-17 07:56
@rcloran Can you make a new release?

**Comment by cgarwood** [comment] 2018-08-30 13:32
Any updates? Seems like @rcloran hasn't been around much lately.

**Comment by AndreasBomholtz** [comment] 2018-08-30 21:26
No, I have not heard anything from him.
So the only thing that I can do is to push it under a new name. Other then that, I do not know what to do.

**Comment by rcloran** [comment] 2018-09-03 16:17
I'll push a new set of releases today.

**Comment by rcloran** [comment] 2018-09-03 16:57
I do want to get #78 fixed first. Seems it shouldn’t be too hard.

**Comment by Gamester17** [comment] 2018-12-05 07:32
Bump this to get a new release in PyPi with support for the newish Ikea Trådfri Plug. Thanks in advance!

**Comment by Hedda** [comment] 2018-12-10 09:11
Please bump PyPi release now that both Aqara Magic Cube and Ikea Trådfri Plug been added

**Comment by Hedda** [comment] 2018-12-21 14:09
Duplicate of #104 however the comments here from @Adminiuga might bare more weight

**Closed** 2019-05-21 14:54 UTC
