### ISSUE TITLE
Ikea Tradifi Update Brick the light

### ISSUE THREAD

**Issue by diegargon** [zigpy/zigpy#1428] opened 2024-07-25 08:26 UTC
Zha update brick two new bulb i buy recently due update

The bulbs (shipped firmware)

TRADFRI bulb E27 WS globe 1055lm
Firmware: 0x03000010

Update to: Firmware: 0x03000022

I have old ones (that update seems not appears)

TRADFRIbulbE27WSglobeopal1055lm
Firmware: 0x00010012

The result is the same that someone posted in this video

https://www.reddit.com/r/tradfri/comments/1e0ohmc/why_are_my_lamps_in_disco_mode/

Seems a known manufacture error:

https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html

as i understand they fixed in 22 no? but no, 22 break that new bulbs

I do not known how ZHA deal with updates but probably will be good if block  updates to this firmware.

**Comment by puddly** [comment] 2024-07-25 13:39
We disable IKEA updates by default and rely on the manufacturer to not push bad updates. I'll see what can be done though.

**Comment by MattWestb** [comment] 2024-07-26 08:13
@puddly Dont  disabling it then IKEA have released one fixed firmware  its in the reseal notes https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html (and reddit post from IKEA) and its some more updates for gen  3 light released last days that is working OK.

If have getting broke devices goo back to IKEA and return / change them it shall not being any problems at all.

(its not one test feed that was braking devices for some years ago its the production feed = garantie is valid  then TF and DG is doing the same)


If like playing safe the user shall not have OTA active and if shall looking if the OTA for the device is working OK from feedback before updating it (like with all fixes from manufacture like MS and co and so on).

**Comment by puddly** [comment] 2024-07-26 14:09
@MattWestb  I'm seeing in the Reddit thread a lot of people mention that `3.0.22` bricked it. I think we can just disable updates for this specific device until this is confirmed fixed.

In the future, I'm hoping to set up https://github.com/zigpy/ota and have all OTA updates from all manufacturers committed to the repository as pull requests. Beta users can install them immediately. Stable users only get the update after a week or two.

**Comment by puddly** [comment] 2024-07-26 14:43
I'm actually not able to find `0x03000022` (`50331682`) at all in the current DIRIGERA JSON:

```console
$ curl -k -L 'https://fw.ota.homesmart.ikea.com/DIRIGERA/version_info.json' | jq
```

<details>
<summary>Output</summary>

```json
[
  {
    "fw_image_type": 10242,
    "fw_type": 2,
    "fw_sha3_256": "e68e61bd57291e0b6358242e72ee2dfe098cb8b769f572b5b8f8e7a34dbcfaca",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/mgm210l-light-cws-cv-rgbw_release_prod_v268572245_3ae78af7-14fd-44df-bca2-6d366f2e9d02.ota"
  },
  {
    "fw_update_prio": 5,
    "fw_filesize": 262600739,
    "fw_type": 3,
    "fw_hotfix_version": 0,
    "fw_major_version": 2,
    "fw_binary_checksum": "7c5fbb0ada1f6f01b516129604e70bf09cd4fdefc2e09dac58eb05e722c6781d8baafb81287933e2149b4003dcd52b83b6265436cbd40625c9cff58080cb94ad",
    "fw_minor_version": 588,
    "fw_sha3_256": "f73d1ab3ff9677d9cee8d3b0da81aec708213367908eb4d2d09af0d26244875a",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/DIRIGERA_release_prod_v2.588.0_24d89869-0b44-4a58-b29f-c5d3127d3931.raucb"
  },
  {
    "fw_image_type": 6456,
    "fw_type": 2,
    "fw_sha3_256": "ad623ed146226dc17b76b71a7a8414c6e550cfe29513580bd4d9269bc7578b2b",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/motionsensor-lds-mg21a_release_prod_v16777316_3a00064a-cc29-4aac-bdb6-c4fa1fb445d5.ota"
  },
  {
    "fw_image_type": 4545,
    "fw_type": 2,
    "fw_sha3_256": "d36803d6dea5f86bc3aea3b3ff7fd46d5d2187b61209cf68ceea2474e85a5f48",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-controller_release_prod_v604241925_abef4451-762a-4ef9-8c11-dfd88c3e98f7.ota"
  },
  {
    "fw_image_type": 4554,
    "fw_type": 2,
    "fw_sha3_256": "3c8cd9a5eee7e1b35a187e84a91db5d2bc91fd98c27f349548ae211eb233720d",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-dimmer_release_prod_v604241925_ecbb4451-ce85-4e6c-ab9f-e7ce32cd0c1e.ota"
  },
  {
    "fw_image_type": 4548,
    "fw_type": 2,
    "fw_sha3_256": "81edaa25a0e5c31a594b41551f1ebdede6c5f94b58e2dfe5462915fc0d4fc637",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-motion-sensor_release_prod_v604241925_e006dcd0-d37e-49db-9a61-6575cb5c44d3.ota"
  },
  {
    "fw_image_type": 16897,
    "fw_type": 2,
    "fw_sha3_256": "87b25a4ca55b1920d50defffd1bd459f0c90a9af0adc6e51609ebd384d6e78ac",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-driver-lp_release_prod_v587757105_b28cda41-22d2-446b-b3bf-5ca11d866719.ota"
  },
  {
    "fw_image_type": 4550,
    "fw_type": 2,
    "fw_sha3_256": "ce7b04ec3ccaa18e0b8b6a085a61c9526e3bacdc6b3513352ac62d2689b066eb",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-shortcut-button_release_prod_v604241926_56f5d8d1-78b1-4088-afc1-05d3b7e3314b.ota"
  },
  {
    "fw_image_type": 8710,
    "fw_type": 2,
    "fw_sha3_256": "4992557dad942e9b56f7171c34186005e1b329a57cc23c9c140addfd153eedd9",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-ws-soc_release_prod_v50331664_500d55d8-d55d-46f0-9afd-68d88ec514dd.ota"
  },
  {
    "fw_image_type": 8449,
    "fw_type": 2,
    "fw_sha3_256": "6c543711e4e7cc88392097588c0d1a05228ae089e9bd2a9b5d1fb1b0b3ce76bb",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-bulb-w-1000lm_release_prod_v587810353_5a161508-742d-4eab-8761-286c80d116eb.ota"
  },
  {
    "fw_image_type": 16898,
    "fw_type": 2,
    "fw_sha3_256": "c60d3ced6fc1a5c0d32f8044f28f19c4e324c2b105a39d1666871036ced68222",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-driver-hp_release_prod_v587757105_b42c57bf-cb9c-478c-8327-5812a3286a64.ota"
  },
  {
    "fw_image_type": 8708,
    "fw_type": 2,
    "fw_sha3_256": "406ffad6d70c5d59faeaaaea63d42abfa9399cf5a7f3d91be10673fd37a2766a",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-kt-bulb-hwpwmcs-ws_release_prod_v16842784_32dc5ff1-4fa4-4960-a847-5e548a81047c.ota"
  },
  {
    "fw_image_type": 4555,
    "fw_type": 2,
    "fw_sha3_256": "967dc9224f8ea9b06f5f5f7d0cc93cdcad2b9a4c7424689fd24b1deaaf637db0",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-kt-styrbar-remote_release_prod_v33816598_c00d5422-e816-48ec-87a6-40198661d2d5.ota"
  },
  {
    "fw_image_type": 4552,
    "fw_type": 2,
    "fw_sha3_256": "1b5fbea79c5b41864352a938a90ad25d9a0118054bf1cdc0314ef9636a60143a",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-motion-sensor2_release_prod_v604241925_8afa2f7c-19c3-4ddf-a96c-233714179022.ota"
  },
  {
    "fw_image_type": 15112,
    "fw_type": 2,
    "fw_sha3_256": "fbabe810f1105152fab706f115c4c2fa21b05e0d61a0bdf06552851c634d5345",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/rodret-shortcut-soc_release_prod_v16777249_d89ffc33-55d1-4d47-acac-42365e5d9dd8.ota"
  },
  {
    "fw_image_type": 4367,
    "fw_type": 2,
    "fw_sha3_256": "029b49416e475ddfb6bd2abfdd47ba279062646cb88940d647cae51b295f5a7f",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-ikea-vindstyrka_release_prod_v16777233_c0532d00-594a-4e10-bb82-1b80d5b6ed87.ota"
  },
  {
    "fw_image_type": 4487,
    "fw_type": 2,
    "fw_sha3_256": "0bf36e39770f508fa96aeb6c5ed6de2d062351197b783cbe72dad720048cd20f",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-connected-blind_release_prod_v604241939_89e61475-8999-4074-842a-e04efac9c857.ota"
  },
  {
    "fw_image_type": 16902,
    "fw_type": 2,
    "fw_sha3_256": "13a15addaef498471f2d4475847769d798f4f14e210874faa02a2f1a1ba1b2a5",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-cv-cct-unified_release_prod_v587757105_33e34452-9267-4665-bc5a-844c8f61f063.ota"
  },
  {
    "fw_image_type": 16901,
    "fw_type": 2,
    "fw_sha3_256": "8951ac2ab9584249b7edf1ca245032f0f9d6fb65e121d268230f49b76ce04dad",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-sy5882-unified_release_prod_v587757105_d478807c-f16e-4989-a948-82818fb545b9.ota"
  },
  {
    "fw_image_type": 51017,
    "fw_type": 2,
    "fw_sha3_256": "6733ab9abdec5a9a7f303e3b9d8ad4cf847aa346270cc0f5526fb61471eb2544",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-jetstrom-cws_release_prod_v16777268_023f19b9-f55b-4c94-a3fe-00c97755eb78.ota"
  },
  {
    "fw_image_type": 16643,
    "fw_type": 2,
    "fw_sha3_256": "2ca4e43497f274d43e340ac6721e221739743a1332ebdcfe1dfd1c2282e14f00",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-light-unified-w_release_prod_v587806257_147c8812-e7f3-4999-b7eb-3da91009ab65.ota"
  },
  {
    "fw_image_type": 8450,
    "fw_type": 2,
    "fw_sha3_256": "53b63d510bd868078bf53f345b31e88167ef10890ea843a20f7a28c7ed5815e7",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-lds-bulb-hwpwm-ww_release_prod_v16842756_529d7965-cee3-4c32-bd28-e5dd17ddc256.ota"
  },
  {
    "fw_image_type": 4354,
    "fw_type": 2,
    "fw_sha3_256": "8401788edc74c2e417011f1b913fa3391f5cc3f12487c4647089e19fbde20381",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-signal-repeater_release_prod_v587753009_3ce8f096-bd12-4b2c-b66e-51dc9f2637dc.ota"
  },
  {
    "fw_image_type": 16645,
    "fw_type": 2,
    "fw_sha3_256": "c1b55ce8de192c7e8c9510f3668fb1a3bc0c1811f946012060054870ca383c24",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-lds-stoftmoln_release_prod_v65542_3388635f-aa73-40e0-8edb-50cd242b72f1.ota"
  },
  {
    "fw_image_type": 8707,
    "fw_type": 2,
    "fw_sha3_256": "64f4627df80227872bfc65cda8e64c42288e75e2e22fd784e5eb5674f546c356",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-bulb-ws-gu10_release_prod_v587757105_25ac125d-5723-4b92-aa02-404fd5008a55.ota"
  },
  {
    "fw_image_type": 16649,
    "fw_type": 2,
    "fw_sha3_256": "3815222125490d9ad331e967dba34700733d12ad6ec3776f19b1a7092c3bbc2c",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-driver-zingo_release_prod_v16777220_1fd2b92c-45c5-44d0-97c5-5c71c2ecb8d2.ota"
  },
  {
    "fw_image_type": 8709,
    "fw_type": 2,
    "fw_sha3_256": "a9a4d6814c2302ba46cd71e7a1e80c192a17accf78ab17eeaa31bb1a8a39459e",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-lds-bulb-hwpwmcs-ws_release_prod_v65554_5d50205c-63c3-426d-bfba-4839c4b55bba.ota"
  },
  {
    "fw_image_type": 8448,
    "fw_type": 2,
    "fw_sha3_256": "2bfd7a648dbe954812a72ab16fc9201dcf2efdb7ff0d9d178ee5a9f00f65a151",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-ww_release_prod_v16777282_a39f1e76-af87-4f04-bd7f-0faf71baf3e4.ota"
  },
  {
    "fw_image_type": 4366,
    "fw_type": 2,
    "fw_sha3_256": "b72a646849f3494adc0690b799b017eb8e78079bae8bf71df692c5d89bc7219f",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/symfonisk-sound-remote-zingo_release_prod_v16777269_1fcbd170-5b54-49e8-896e-16a73ca72011.ota"
  },
  {
    "fw_image_type": 4353,
    "fw_type": 2,
    "fw_sha3_256": "01a742d63d0b247259068b729edace2929af8f946a8df2334e3025f59cb4cff1",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-control-outlet_release_prod_v587765297_20061876-85d6-4b39-8c9c-eb95620baa97.ota"
  },
  {
    "fw_image_type": 4357,
    "fw_type": 2,
    "fw_sha3_256": "725e953c3a9507a921a533b04ae1231d0c16ccc57080d81acfdc130e18066426",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-jetstrom-ws_release_prod_v33816584_33813e5d-0cc9-4b4a-9e93-9000ee44cbe4.ota"
  },
  {
    "fw_image_type": 16900,
    "fw_type": 2,
    "fw_sha3_256": "754eb2e6b4867d4972e43441cbef9306537eaf4dc41b30bfd3163b1b69c67050",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-sy5882-bulb-ws_release_prod_v587814449_185b3c4d-da1b-4867-8c16-2cee1fc5c11d.ota"
  },
  {
    "fw_image_type": 4546,
    "fw_type": 2,
    "fw_sha3_256": "b39c08132728c048ebcc90093f74fd355cefce64f84d061560aa1c57ed38b39c",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-wireless-dimmer_release_prod_v587367985_87ff9a75-c4e3-4999-a654-09bb8638f4cc.ota"
  },
  {
    "fw_image_type": 16899,
    "fw_type": 2,
    "fw_sha3_256": "cc22b85ca4ba06acf8047b31234b137fcd084d45660bb7373d2c67c3ed8b0329",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-sy5882-driver-ws_release_prod_v587798065_479fc716-673b-4731-bbb7-86833c456e4c.ota"
  },
  {
    "fw_image_type": 16641,
    "fw_type": 2,
    "fw_sha3_256": "95c154a0a97f1276ae5f53b50ee5ee99e31dcf96d7199b2708262a40707e5771",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-transformer_release_prod_v587753009_17d32c23-151f-44cb-a947-4c13a78f36e6.ota"
  },
  {
    "fw_image_type": 10245,
    "fw_type": 2,
    "fw_sha3_256": "0ee2edd8c4efbba03c02900c75336a472010599c97aeb2e539c4821c5e31ee6c",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-cws_release_prod_v16777272_89b37a10-683a-4183-9ed7-4973bc34994b.ota"
  },
  {
    "fw_image_type": 8705,
    "fw_type": 2,
    "fw_sha3_256": "394c0836a5e77883c2710c6c0a1f1a33d34583f4502300aab3fc471bb6aba03f",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-bulb-ws-e14_release_prod_v587757105_963ac72a-97be-4f7e-b12c-46759bb91d6e.ota"
  },
  {
    "fw_image_type": 8706,
    "fw_type": 2,
    "fw_sha3_256": "9318a9cfbb6aef7bc50586d9b16a3a39b470fa6c88e4fd05f5f77834f9ceeceb",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-bulb-ws-1000lm_release_prod_v587814449_2b13625e-17a8-40d9-bad3-47a9a96ab002.ota"
  },
  {
    "fw_image_type": 8704,
    "fw_type": 2,
    "fw_sha3_256": "b3fec5e75bb4c529b84bd2e92a40146d992672d6afe943aef8349ccfaa0695cd",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-ws_release_prod_v50331681_969bee21-eca6-4f10-a4c0-9685c0cd5d52.ota"
  },
  {
    "fw_image_type": 4365,
    "fw_type": 2,
    "fw_sha3_256": "2512a74ba20f445494e75f9f05c4debf051cff14496af2abad7a2074d635b6d3",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-lds-plugin-unit_release_prod_v65538_b29c3768-a102-4414-a84d-405c99654e74.ota"
  },
  {
    "fw_image_type": 4557,
    "fw_type": 2,
    "fw_sha3_256": "55a69e55d4edff076e0702dd260011f26a32352404a3227afa4f274e3c9958a2",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/rodret-dimmer-soc_release_prod_v16777303_0a78457a-950c-4903-bfd1-67902aa66cf9.ota"
  },
  {
    "fw_image_type": 4364,
    "fw_type": 2,
    "fw_sha3_256": "80c8b788ff094b3943d8b74bebefba8b73df2c526602bca0da126e777dca3f73",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-lds-starkvind_release_prod_v69633_2044addf-0a35-4845-b851-74df04ab3a76.ota"
  },
  {
    "fw_image_type": 4549,
    "fw_type": 2,
    "fw_sha3_256": "499f08c42fdcd5019c8d48b3a17c2f3406cdc97b4bfb41db064a1487e695596c",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-onoff-controller_release_prod_v604241926_3c2e5569-667c-49ed-a286-78a0e031935d.ota"
  },
  {
    "fw_image_type": 16644,
    "fw_type": 2,
    "fw_sha3_256": "f546464079b5e3c03862acfa03dcba693e03155681cd07c67c3f0b12558d7987",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-sigma-driver-silverglans-ww_release_prod_v65569_73466dc4-1320-4242-add6-717432538a77.ota"
  },
  {
    "fw_image_type": 10241,
    "fw_type": 2,
    "fw_sha3_256": "e718abba1958fe7e00297a1c143033d8505b26b67d2668faf08bc137cc27ba00",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/tradfri-bulb-cws-zll_release_prod_v587753009_ec8b1193-0fa2-440e-b921-2412a8688b74.ota"
  }
]
```
</details>

The only similar image is this one:

```json
  {
    "fw_image_type": 8704,
    "fw_type": 2,
    "fw_sha3_256": "b3fec5e75bb4c529b84bd2e92a40146d992672d6afe943aef8349ccfaa0695cd",
    "fw_binary_url": "https://fw.ota.homesmart.ikea.com/files/zingo-ws_release_prod_v50331681_969bee21-eca6-4f10-a4c0-9685c0cd5d52.ota"
  },
```

And it is version `50331681`, not `50331682`. Seems to be `3.0.21`? Maybe IKEA pulled 3.0.22.

Just to be safe, is `image_type: 8704` the only affected bulb?

**Comment by MattWestb** [comment] 2024-07-26 15:28
Its only in TF feed like some other not certificated (or at least published) firmware.
Others is only DG so IKEA is messing  around little for the moment.

From my download script it  shall being `zingo_ww-0x2100-1.0.42-prod.ota.ota.signed`.
(Also TF cant being browsed so they have doing more work on its clod storage for making  it worse flowing what s happening)


Edit: The reddit was only punting to the WW version but one WS is also updated `zingo_ws_soc-0x2206-3.0.22-prod.ota.ota.signed`.


Edit 2:

Buggy  version was:

TRÅDFRI white spectrum bulb E14/GU10 (3.0.21)
Product ID: LED2106, LED2107
◆ Update to support new product revisions.


Updated version in feed is:

TRÅDFRI white spectrum bulb E27 (3.0.22)
Product ID: LED2201
◆ Bug fixes.


Do its not  my fist linked firmware its the second WS.

**Comment by MattWestb** [comment] 2024-07-26 15:54
The `TRADFRIbulbE27WSglobeopal1055lm` is Gen3 but have no resent update and is not being broken.
From my test device:

Device info
TRADFRIbulbE27WSglobeopal1055lm
by IKEA of Sweden
Connected via [IKEA Billy EZSP 6.10.7.0](http://192.168.2.66:8123/config/devices/device/9b13acab058111ebb300cf2132e87262)
Firmware: 0x00010012

The Gen  1/2 (Im wrong its one 3 gen device with strange version) firmware from TF feed for Puddly:
[zingo_ws_soc-0x2206-3.0.22-prod.ota.ota.zip](https://github.com/user-attachments/files/16393962/zingo_ws_soc-0x2206-3.0.22-prod.ota.ota.zip)

Its Hex/ dec 0x2206 8710 image number.

**Comment by puddly** [comment] 2024-07-26 16:10
Thanks! So will blocking `8710` for IKEA be enough then to prevent updates for this specific device? Or is there a second variant (`zingo-ws` has two types, the other being `8704`)?

**Comment by MattWestb** [comment] 2024-07-26 16:19
The `zingo_ws | 0x2200 8704` is OK was getting  devices 4 updated early this morning (TF feed).
(just sniffed one new request for verification and its the right working on for the image) 

I dont have the image in version 3.0.21 but that  shall being the braking one and its update in TF to 3.0.22 so shall being OK but i dont know the DG feed is updating so  you need looking on it.

**Comment by TheJulianJES** [comment] 2024-07-26 16:42
To make sure I understand everything correctly, @MattWestb:
1. The broken update that bricked devices was already pulled by IKEA, right? (yes/no)
2. The broken update was replaced by a newer update that no longer bricks bulbs? (yes/no)
3. Already bricked bulbs have to be exchanged at IKEA. You cannot update them now. (yes/no)

If the assumptions are correct, is there any reason to still block firmware updates for that device then?

**Comment by puddly** [comment] 2024-07-26 16:52
Here's what I get for all three feeds:

```python
In [1]: from zigpy.ota.providers import Tradfri

In [2]: dirigera = await Tradfri('https://fw.ota.homesmart.ikea.com/DIRIGERA/version_info.json').load_index()

In [3]: ikea_old = await Tradfri('http://fw.ota.homesmart.ikea.net/feed/version_info.json').load_index()

In [4]: ikea_old_test = await Tradfri('https://fw.test.ota.homesmart.ikea.net/feed/version_info.json').load_index()

In [5]: [i for i in dirigera if i.image_type == 8704]
Out[5]: [IkeaRemoteOtaImageMetadata(file_version=50331681, manufacturer_id=4476, image_type=8704, checksum='sha3-256:b3fec5e75bb4c529b84bd2e92a40146d992672d6afe943aef8349ccfaa0695cd', file_size=None, manufacturer_names=(), model_names=(), changelog=None, release_notes=None, min_hardware_version=None, max_hardware_version=None, min_current_file_version=None, max_current_file_version=None, specificity=None, source='IKEA (DIRIGERA)', url='https://fw.ota.homesmart.ikea.com/files/zingo-ws_release_prod_v50331681_969bee21-eca6-4f10-a4c0-9685c0cd5d52.ota', ssl_ctx=None)]

In [6]: [i for i in ikea_old if i.image_type == 8704]
Out[6]: [SignedIkeaRemoteOtaImageMetadata(file_version=50331681, manufacturer_id=4476, image_type=8704, checksum=None, file_size=307758, manufacturer_names=(), model_names=(), changelog=None, release_notes=None, min_hardware_version=None, max_hardware_version=None, min_current_file_version=None, max_current_file_version=None, specificity=None, source='IKEA (TRÅDFRI)', url='https://fw.ota.homesmart.ikea.net/global/GW1.0/01.21.031/bin/zingo_ws-0x2200-3.0.21-prod.ota.ota.signed', ssl_ctx=None)]

In [7]: [i for i in ikea_old_test if i.image_type == 8704]
Out[7]: []
```

So it looks like `3.0.21` is the only firmware available. It *sounds* on Reddit like the `3.0.21` update was the bad one? Or maybe it's the last firmware version that could be read from the device, so it was the `3.0.22` update that broke these bulbs?

---

I say we block all updates for 8704 from IKEA until they explicitly say they've fixed this problem. If the bulb is broken, an update won't fix it.

**Comment by puddly** [comment] 2024-07-26 16:56
@diegargon Can you post your ZHA OTA config? Are you using the default IKEA provider (DIRIGERA) or did you manually use the old URL?

---

The last 64 bytes of the flash data in the firmwares themselves differ between the DIRIGERA and the test feed firmwares, I'm wondering if the test feed is broken? I noticed only two reports from ZHA users overall, everything else is coming from Z2M. We don't use the test feed unless you manually configure it.

**Comment by MattWestb** [comment] 2024-07-26 17:17
From time machine:


15/7: http://fw.ota.homesmart.ikea.net/global/GW1.0/01.21.031/bin/zingo_ws_soc-0x2206-3.0.21-prod.ota.ota.signed"

25/7: http://fw.ota.homesmart.ikea.net/global/GW1.0/01.21.031/bin/zingo_ws_soc-0x2206-3.0.22-prod.ota.ota.signed"

So IKEA have putting out one update after the  request they was doing on reddit and also doing the release notes.

My TF script is getting the 3.0.22 for  5 minutes ago so little strange that you is getting the 3.0.21 puddly.

**Comment by MattWestb** [comment] 2024-07-26 17:31
> The last 64 bytes of the flash data in the firmwares themselves differ between the DIRIGERA and the test feed firmwares, I'm wondering if the test feed is broken?

Perhaps have use different signing key or padding the end before the CRC and / or  the signing.

Can  you finding 0x2206 / 8710 in Dirigera feed  ??
If not then  TF is working OK then its coming from it for my updated GU10 WS (or can being DG if its also the).

**Comment by MattWestb** [comment] 2024-07-26 17:33
@puddly have you restarting HA  for getting the update feed then its looks strange you is getting one old version from it ?

Time machine link: https://web.archive.org/web/20240000000000*/http://fw.ota.homesmart.ikea.net/feed/version_info.json

**Comment by puddly** [comment] 2024-07-26 18:42
Strange. The code I ran above was outside of Home Assistant, it was just zigpy and shouldn't be caching anything. I'll try again later tonight and change the URLs to invalidate the cache (adding `?somerandomtext` might work)

**Comment by puddly** [comment] 2024-07-26 20:40
Ahh, we're looking at different data. I was looking at 8704, not 8710! Here is all of the data:

| Image Type |   Feed   |    Version   |
| --------------- | -------- | ------------ |
| 8710            | DIRIGERA | `0x03000010` |
| 8710            | Old OTA  | `0x03000022` |
| 8704            | DIGIGERA | `0x03000021` |
| 8704            | Old OTA  | `0x03000021` |

So for 8710, DIRIGERA is still on 3.0.10 but the old OTA feed is on 3.0.22, the broken version? 8704 is on 3.0.21 for both feeds.

I think 8710 is the only affected device, 8704 isn't affected. And it looks like the old OTA feed is still pushing the bad image...

**Comment by MattWestb** [comment] 2024-07-26 21:16
The` zingo_ws | 0x2200 8704` is OK.
0x2206 8710 `zingo_ws_soc-0x2206-3.0.22-prod.ota.ota.signed` from TF shall being the fixed version (was  reading little more on reddit and possible recover if not re-power  the device and if done = hard braked device) and Dirigera  is being hold back = OK then its costing little braking some hundred thousand devices.

So IKEA have all feed fixed or held back (and very likely not rolling out the braked version in DG feed).

**Comment by MattWestb** [comment] 2024-07-26 21:28
No need  blocking  `zingo_ws` | 0x2200 / 8704 its working OK.

![IkeaOTA01](https://github.com/user-attachments/assets/fe7d9903-6c6e-40e7-be50-9a2788e2d704)

I have 4 in production and 2 in RCP test updated and working OK

**Comment by diegargon** [comment] 2024-07-26 22:37
> @diegargon Can you post your ZHA OTA config? Are you using the default IKEA provider (DIRIGERA) or did you manually use the old URL?
> 
> The last 64 bytes of the flash data in the firmwares themselves differ between the DIRIGERA and the test feed firmwares, I'm wondering if the test feed is broken? I noticed only two reports from ZHA users overall, everything else is coming from Z2M. We don't use the test feed unless you manually configure it.

I  did nothing special, i just only have this in my configuration file.

zha:
  database_path: /config/zigbee.db 
  enable_quirks: true
  custom_quirks_path: /config/custom_zha_quirks
  zigpy_config:
    ota:
      otau_directory: /config/zigpy_ota
      ikea_provider: true
     sonoff_provider: true

When i connect the 3 new lights the update appears in HA,  22 version not 21,  i click update  two of them and they broke

The survive light (i not  update):

TRADFRI bulb E27 WS globe 1055lm
por IKEA of Sweden
Firmware: 0x03000010
Zigbee info
IEEE: b0:c7:de:ff:fe:64:dd:58
Nwk: 0x8667
Device Type: Router
LQI: 168
RSSI: -58
Visto por última vez: 2024-07-27T00:29:28
Fuente de alimentación: Mains


One of the dead:

TRADFRI bulb E27 WS globe 1055lm
por IKEA of Sweden
Firmware: 0x03000022
Zigbee info
IEEE: b0:c7:de:ff:fe:64:40:f4
Nwk: 0x8b04
Device Type: Router
LQI: Desconocido
RSSI: Desconocido
Visto por última vez: 2024-07-24T20:48:34
Fuente de alimentación: Mains

**Closed as completed** 2024-07-29 16:40 UTC

**Comment by danielsteiner** [comment] 2025-10-20 20:54
This issue was closed as compleded a bit more than a year ago without further information. 

The wiki still states, that the IKEA OTA config is disabled because it can brick bulbs - is this still correct or is this issue resolved and can users safely activate the IKEA config?

**Comment by puddly** [comment] 2025-10-20 21:04
We have not explored ways to safely enable it yet. In the next few releases I expect us to have a beta system to community vet the updates before promoting them to stable.

**Comment by danielsteiner** [comment] 2025-10-20 21:05
Awesome, thanks for the quick heads up! In that case I'll keep it disabled _for now_

**Comment by MattWestb** [comment] 2025-10-21 07:32
IKEA have stable OTA feed now bit its not the first time and not the last they is getting problems then they is updating (nearly) all there devices, First was the first gen CWS update to Zigbee 3 from ZLL and in the end they was doing 2 different device images for updated one one for old version.
For the moment i see IKEA OTA feed stable then its not updated for nearly one year and both TO and DG is updating all devices OK (only some controllers can having problems rolling back).

IKEA is holding one large bunch device updates (CSA certified) but i think they is doing them active then rolling out Zigbee/Thread(Matter) cross platform for (Gen 3 +) of devices with MG24 chips and getting one Zigbee and/or thread / Matter device with OTA.
